const actionTypes = {
  UPDATE_RAW_CARD_LIST: 'UPDATE_RAW_CARD_LIST',
  UPDATE_FETCHING_INITIAL_DECK_LIST: 'UPDATE_FETCHING_INITIAL_DECK_LIST',
  UPDATE_INITIAL_CARD_LIST: 'UPDATE_INITIAL_CARD_LIST',
};

export default actionTypes;